# Generated by Django 4.0 on 2022-02-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldage_members',
            name='oldage_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oldage_members',
            name='bank',
            field=models.CharField(max_length=100),
        ),
    ]
