# Generated by Django 4.0 on 2022-02-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldage', '0002_oldage_members_oldage_id_alter_oldage_members_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldage_donation',
            name='society',
            field=models.CharField(default='oldage', max_length=50),
            preserve_default=False,
        ),
    ]
