# Generated by Django 4.0 on 2022-02-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldage', '0004_rename_disctrict_oldage_donation_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldage_members',
            name='dob',
            field=models.CharField(max_length=100),
        ),
    ]
