# Generated by Django 4.0 on 2022-02-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage_members',
            name='orphanage_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
