# Generated by Django 4.0 on 2022-02-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0002_orphanage_members_orphanage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage_donation',
            name='society',
            field=models.CharField(default='orphanage', max_length=50),
            preserve_default=False,
        ),
    ]
