# Generated by Django 4.0 on 2022-02-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0004_rename_disctrict_orphanage_donation_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orphanage_product',
            old_name='member_id',
            new_name='society_id',
        ),
        migrations.AddField(
            model_name='orphanage_purchase',
            name='society_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
