# Generated by Django 4.0 on 2022-02-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0005_rename_member_id_orphanage_product_society_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orphanage_purchase',
            name='society_id',
        ),
        migrations.AddField(
            model_name='orphanage_purchase',
            name='society',
            field=models.CharField(default='orphanage', max_length=50),
            preserve_default=False,
        ),
    ]
