# Generated by Django 4.0 on 2022-02-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0006_remove_orphanage_purchase_society_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orphanage_purchase',
            old_name='disctrict',
            new_name='district',
        ),
    ]
